// Auto-generated by Supabase (supabase gen types) for the Buckme project.
// Regenerate after schema changes; keep in sync with the public schema.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admin_config: {
        Row: { created_at: string; id: string; secret: string }
        Insert: { created_at?: string; id?: string; secret: string }
        Update: { created_at?: string; id?: string; secret?: string }
        Relationships: []
      }
      lead_events: {
        Row: {
          created_at: string
          detail: string | null
          from_stage: string | null
          id: string
          lead_id: string
          to_stage: string | null
          type: string
        }
        Insert: {
          created_at?: string
          detail?: string | null
          from_stage?: string | null
          id?: string
          lead_id: string
          to_stage?: string | null
          type: string
        }
        Update: {
          created_at?: string
          detail?: string | null
          from_stage?: string | null
          id?: string
          lead_id?: string
          to_stage?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_events_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_notes: {
        Row: {
          author: string
          body: string
          created_at: string
          id: string
          lead_id: string
        }
        Insert: {
          author?: string
          body: string
          created_at?: string
          id?: string
          lead_id: string
        }
        Update: {
          author?: string
          body?: string
          created_at?: string
          id?: string
          lead_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_notes_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          amount: number | null
          created_at: string
          email: string | null
          first_name: string | null
          frequency: string | null
          id: string
          mobile: string | null
          purpose: string | null
          source: string | null
          stage: string
          status: string
          term_months: number | null
          updated_at: string
        }
        Insert: {
          amount?: number | null
          created_at?: string
          email?: string | null
          first_name?: string | null
          frequency?: string | null
          id?: string
          mobile?: string | null
          purpose?: string | null
          source?: string | null
          stage?: string
          status?: string
          term_months?: number | null
          updated_at?: string
        }
        Update: {
          amount?: number | null
          created_at?: string
          email?: string | null
          first_name?: string | null
          frequency?: string | null
          id?: string
          mobile?: string | null
          purpose?: string | null
          source?: string | null
          stage?: string
          status?: string
          term_months?: number | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      admin_add_note: {
        Args: { p_author?: string; p_body: string; p_id: string; p_secret: string }
        Returns: {
          author: string
          body: string
          created_at: string
          id: string
          lead_id: string
        }
      }
      admin_get_lead: {
        Args: { p_id: string; p_secret: string }
        Returns: Json
      }
      admin_list_leads: {
        Args: { p_secret: string }
        Returns: {
          amount: number | null
          created_at: string
          email: string | null
          first_name: string | null
          frequency: string | null
          id: string
          mobile: string | null
          purpose: string | null
          source: string | null
          stage: string
          status: string
          term_months: number | null
          updated_at: string
        }[]
      }
      admin_set_stage: {
        Args: { p_id: string; p_secret: string; p_stage: string }
        Returns: {
          amount: number | null
          created_at: string
          email: string | null
          first_name: string | null
          frequency: string | null
          id: string
          mobile: string | null
          purpose: string | null
          source: string | null
          stage: string
          status: string
          term_months: number | null
          updated_at: string
        }
      }
      admin_stats: { Args: { p_secret: string }; Returns: Json }
      submit_lead: {
        Args: {
          p_first_name: string
          p_email: string
          p_mobile: string
          p_amount: number
          p_frequency: string
          p_purpose: string
          p_source: string
          p_term_months?: number
        }
        Returns: string
      }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
