// Auto-generated by Supabase (supabase gen types) for the Buckme project.
// Regenerate after schema changes; keep in sync with public.leads.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      leads: {
        Row: {
          amount: number | null
          created_at: string
          email: string | null
          first_name: string | null
          frequency: string | null
          id: string
          mobile: string | null
          purpose: string | null
          source: string | null
          status: string
        }
        Insert: {
          amount?: number | null
          created_at?: string
          email?: string | null
          first_name?: string | null
          frequency?: string | null
          id?: string
          mobile?: string | null
          purpose?: string | null
          source?: string | null
          status?: string
        }
        Update: {
          amount?: number | null
          created_at?: string
          email?: string | null
          first_name?: string | null
          frequency?: string | null
          id?: string
          mobile?: string | null
          purpose?: string | null
          source?: string | null
          status?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
